build:
  image: golang:1.5
  environment:
    - GO15VENDOREXPERIMENT=1
    - GOOS=linux
    - GOARCH=amd64
    - CGO_ENABLED=
    - GOPATH=
  commands:
    - go get -v github.com/tools/godep
    - go get gopkg.in/yaml.v2
    - godep restore
    - go test
    - go build -a -tags netgo

publish:
  docker:
    image: leankit/drone-docker
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: leankit/drone-cowpoke
    storage_driver: overlay
    when:
      branch: master

plugin:
  name: Cowpoke
  desc: PUT an image to Cowpoke
  type: publish
  image: leankit/drone-cowpoke
  labels:
    - cowpoke
    - rancher
    - image
