build:
  image: golang:1.5
  environment:
    - GO15VENDOREXPERIMENT=1
    - GOOS=linux
    - GOARCH=amd64
    - CGO_ENABLED=0
  commands:
    - go get
    - go build
    - go test

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: leankit/drone-cowpoke
    when:
      branch: master

plugin:
  name: Cowpoke
  desc: PUT an image to Cowpoke
  type: publish
  image: leankit/drone-cowpoke
  labels:
    - docker
    - image
    - container
